alias updatedb='sudo /usr/libexec/locate.updatedb'
alias port-update='sudo port selfupdate && sudo port -u upgrade outdated'
alias mini-server='python3.2 -m http.server'
alias channels='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -s'
alias pwd2clip='pwd | tr -d "\n" | pbcopy'
