#!/usr/bin/env bash

function get_clipboard {
    case $(uname) in
        Linux) xclip -selection c -o;;
        Darwin) pbpaste;;
        CYGWIN*) getclip;;
        *) echo "Unknown OS";;
    esac
}

# via clipboard
if [ "$1" == "clip" ]; then
    echo "CLIP :"
    get_clipboard | openssl x509 -text

# via file
elif [ -f "$1" ]; then
    echo "FILE : $1"
    openssl x509 -text -in "$1"

# or via domain
else
    if [[ "$1" == *:* ]]; then
        HOST="${1%%:*}"
        PORT="${1##*:}"
    else
        HOST="$1"
        PORT=443
    fi

    echo "DOMAIN : $HOST:$PORT"
    echo -n | openssl s_client -connect "$HOST:$PORT" -servername "$HOST" -prexit 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -text
fi