#!/usr/bin/env bash

function get_clipboard {
    case $(uname) in
        Linux)
            xclip -selection c -o
            ;;
        Darwin)
            pbpaste
            ;;
        CYGWIN*)
            getclip
            ;;
        *)
            echo "Unknown OS"
            ;;
    esac
}

# http://stackoverflow.com/a/20046959
DOMAIN=$(echo "$1" | grep -P '^(([a-zA-Z]{1})|([a-zA-Z]{1}[a-zA-Z]{1})|([a-zA-Z]{1}[0-9]{1})|([0-9]{1}[a-zA-Z]{1})|([a-zA-Z0-9][a-zA-Z0-9-_]{1,61}[a-zA-Z0-9]))\.([a-zA-Z]{2,6}|[a-zA-Z0-9-]{2,30}\.[a-zA-Z]{2,3})$')


# via clipboard
if [ "$1" == "clip" ]; then
    echo "CLIP :"
    get_clipboard | openssl x509 -text

# via file
elif [ -f "$1" ]; then
    echo "FILE : $1"
    openssl x509 -text -in "$1"

# or via domain
elif [ -n "$DOMAIN"  ]; then
    echo "DOMAIN : $DOMAIN"
    echo -n | openssl s_client -connect "$DOMAIN":443 2>/dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | openssl x509 -text

# or error
else
    >&2 echo "ERROR: [$1] is not 'clip', a valid file or a valid domain"
fi
