#!/usr/bin/env bash

if ! ([ -d "$1" ] || [ -f "$1" ]); then
    >&2 echo "Could not find $1"
    exit 1
fi

FILENAME=$(realpath "$1")

if [ -d /tmp/codesign ]; then
    rm -r /tmp/codesign
fi
mkdir -p /tmp/codesign
cd /tmp/codesign || exit 1


case "$(uname)" in
    Linux)
        echo "Not yet implemented"
        ;;
    Darwin)
        codesign -dvvvv --extract-certificates "$FILENAME" > /dev/null 2>&1
        ;;
    CYGWIN*)
        powershell -Command "[io.file]::WriteAllBytes( 'codesign0', \$( Get-AuthenticodeSignature '$(cygpath -w "$FILENAME")' ).SignerCertificate.RawData )"
        ;;
    *)
        echo "Error: Unknown OS."
        ;;
esac

openssl x509 -inform DER -in codesign0
