#!/usr/bin/env bash
# script to debug loop a program until it crashes
# https://haaspors.github.io/tools/2015/01/21/gdb-run-until-crash.html


APP="$1"
shift
ARGS="$@"

echo "Looping $APP $ARGS"

echo "
set pagination off
break _fini
commands
    run $ARGS
    end
run $ARGS
"> /tmp/debug_loop.gdb

gdb -x /tmp/debug_loop.gdb "$APP"
