#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $(basename "$0") <file>"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Could not find $1"
    exit 1
fi

BEFORE="$1"
TMPFILE="${BEFORE}.tmp"
LOWER="$(echo "$1" | awk '{print tolower($0)}')"

echo "git: from $BEFORE to $LOWER"

git mv "$BEFORE" "$TMPFILE"
git mv "$TMPFILE" "$LOWER"


