#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Usage: $(basename "$0") <file>"
    exit 1
fi

if [ ! -f "$1" ]; then
    echo "Could not find $1"
    exit 1
fi

cat "$1" | awk '{printf("L%d : %s \n", NR, $0)}' | perl -ne 'print if /[^[:ascii:]]/'
