#!/usr/bin/env bash
# enhanced touch to create executable stubs for common programming languages

if [ "$#" != "1" ]; then
    echo "Usage: $(basename "$0") <filename>"
    exit 1
fi

FILENAME="$1"
BASENAME="$(basename "$FILENAME")"
EXTENSION="${BASENAME##*.}"

# if file exists and is not empty, just make executable
if [ -s "$FILENAME" ]; then
    chmod +x "$FILENAME"
    exit
fi

# if file exists and is not a regular file, return
if [ -e "$FILENAME" ] && [ ! -f "$FILENAME" ]; then
    echo "$FILENAME exists and is not a regular file"
    exit 1
fi

case "$EXTENSION" in
    sh)
        echo -e '#!/usr/bin/env bash\n\necho "Hello"' > "$FILENAME"
        ;;
    cpp)
        cat << EOF > "$FILENAME"
#!/usr/bin/env cppsh
#include <iostream>

int main( int argc, char* argv[] ) {
    std::cout << "Hello" << std::endl;
    return 0;
}
EOF
        ;;
    py)
        cat << EOF > "$FILENAME"
#!/usr/bin/env python3

if __name__ == "__main__":
    print("Hello")
EOF
        ;;
    dart)
        cat << EOF > "$FILENAME"
#!/usr/bin/env dart

int main() {
  print("Hello");
  return 0;
}
EOF
        ;;

    *)
        touch "$FILENAME"
        ;;
esac

chmod +x "$FILENAME"
