#!/usr/bin/env bash

if [ "$#" == 0 ]; then
    echo "Usage: $(basename "$0") filename.json"
    exit 1
fi

python3 -c "import json; f = open('$1'); json.load(f);"

if [ $? -eq 0 ]; then
    echo ok
fi
