#!/usr/bin/env bash

if [ "$1" == "allow" ]; then
    VALUE=0
else
    VALUE=1
fi

SCRIPT=$(cat <<EOF
@echo off
REG ADD "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /f /t REG_DWORD /v fDenyTSConnections /d ${VALUE}
EOF
)

function query_key {
    cmd /c REG QUERY "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections
}

function is_denied {
    query_key | grep -Po "(?<=0x)(\d)"
}

function check_remote {
    if [ "$(is_denied)" == "1" ]; then
        echo -n "Remote connections are denied"
    else
        echo -n "Remote connections are allowed"
    fi
}

if [ "$(is_denied)" == "${VALUE}" ]; then
    echo "Did nothing"
    exit 0
fi

echo "$SCRIPT" > /tmp/allow_remote.bat
COMMAND=$(cygpath -w /tmp/allow_remote.bat)

echo "Before: $(check_remote)"
cygstart --wait --action=runas "$COMMAND"
echo "After:  $(check_remote)"

